-- MySQL Script generated by MySQL Workbench
-- Fri Jun 13 14:27:30 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `notes` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`session` (
  `id` INT NOT NULL,
  `project_id` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `notes` BLOB NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`project_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`individual` (
  `id` INT NOT NULL,
  `notes` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participation` (
  `survey_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `invited` BINARY NULL,
  `identified` BINARY NULL,
  `participated` BINARY NULL,
  `notes` BLOB NULL,
  `pay` DECIMAL(10,2) NULL,
  INDEX `id_idx` (`survey_id` ASC),
  INDEX `id_idx1` (`session_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`session_id`)
    REFERENCES `mydb`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demog_def`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demog_def` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `notes` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category_def`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category_def` (
  `demog_id` INT NOT NULL,
  `value` INT NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `notes` BLOB NULL,
  INDEX `id_idx` (`demog_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`demog_id`)
    REFERENCES `mydb`.`demog_def` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pages` (
  `id` INT NOT NULL,
  `page` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permissions` (
  `id` INT NOT NULL,
  `page_id` INT NOT NULL,
  INDEX `id_idx` (`page_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`page_id`)
    REFERENCES `mydb`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `perm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`permissions` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demog_string`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demog_string` (
  `survey_id` INT NOT NULL,
  `demog_id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `id_idx` (`survey_id` ASC),
  INDEX `id_idx1` (`demog_id` ASC),
  INDEX `id_idx2` (`user_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`demog_id`)
    REFERENCES `mydb`.`demog_def` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demog_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demog_date` (
  `survey_id` INT NOT NULL,
  `demog_id` INT NOT NULL,
  `value` DATETIME NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `id_idx` (`demog_id` ASC),
  INDEX `id_idx1` (`survey_id` ASC),
  INDEX `id_idx2` (`user_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`demog_id`)
    REFERENCES `mydb`.`demog_def` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demog_int`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demog_int` (
  `survey_id` INT NOT NULL,
  `demog_id` INT NOT NULL,
  `value` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `id_idx` (`survey_id` ASC),
  INDEX `id_idx1` (`demog_id` ASC),
  INDEX `id_idx2` (`user_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`demog_id`)
    REFERENCES `mydb`.`demog_def` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demog_float`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demog_float` (
  `survey_id` INT NOT NULL,
  `demog_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `id_idx` (`survey_id` ASC),
  INDEX `id_idx1` (`demog_id` ASC),
  INDEX `id_idx2` (`user_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`demog_id`)
    REFERENCES `mydb`.`demog_def` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`demog_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`demog_category` (
  `survey_id` INT NOT NULL,
  `demog_id` INT NOT NULL,
  `value` INT NOT NULL,
  `time` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `id_idx` (`demog_id` ASC),
  INDEX `id_idx1` (`survey_id` ASC),
  INDEX `id_idx2` (`user_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`demog_id`)
    REFERENCES `mydb`.`demog_def` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`survey_id`)
    REFERENCES `mydb`.`individual` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
